name: Confirm Flaky Test with NonDex

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  run-nondex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Flaky Project Code
      uses: actions/checkout@v3
      with:
        repository: mapstruct/mapstruct
        ref: 26c5bcd923c7206ad161e93237f841a79ca85efd

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Compile the code
      run: mvn clean install -DskipTests -pl processor -am

    - name: Run test normally (Should Pass)
      run: mvn -pl processor test -Dtest=org.mapstruct.ap.test.conversion.java8time.Java8TimeConversionTest#testInstantToStringMapping

    - name: Run NonDex (Should Fail)
      run: mvn -pl processor edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.mapstruct.ap.test.conversion.java8time.Java8TimeConversionTest#testInstantToStringMapping
