name: Confirm Flaky Test with NonDex

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  run-nondex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Flaky Project Code
      uses: actions/checkout@v3
      with:
        repository: kiegroup/jbpm
        ref: f7e80e82b7670c09485ce83869a287ef51dcb59c

    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Compile the code
      run: mvn clean install -DskipTests -pl jbpm-case-mgmt/jbpm-case-mgmt-impl -am

    - name: Run test normally (Should Pass)
      run: mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl test -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testCaseWithIndexedFromVariableUpdates

    - name: Run NonDex (Should Fail)
      run: mvn -pl jbpm-case-mgmt/jbpm-case-mgmt-impl edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.jbpm.casemgmt.impl.CaseServiceImplTest#testCaseWithIndexedFromVariableUpdates
